### ISSUE TITLE
Is Remote Display deprecated in google cast SDK 3.0?

### ISSUE THREAD

**Issue by ghost** [googlecast/CastVideos-android#10]
Hi,

I keep seeing:
Version warning: This page and the Remote Display API are for use only with Cast SDK v2 and must not be mixed with v3.

I would like to know if Remote Display API (https://developers.google.com/cast/docs/remote) is supported in Google Cast SDK 3.*.

Thanks!

**Comment by entertailion** [comment]
We are still actively developing and optimizing Remote Display. We have found that the development for Remote Display type products has slightly different needs and requirements than Casting media and are taking this into consideration as we think about the next generation of RD. Stay tuned and please provide feedback if there's an RD area you think we should improve.
