### ISSUE TITLE
Fatal Exception: android.app.ForegroundServiceStartNotAllowedException in Android 12 devices

### ISSUE THREAD

**Issue by markshim1** [googlecast/CastVideos-android#115]
Hi, I have an issue with this crash.
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/7144761/151451739-9b31fb00-63ba-4b00-a4ef-f60d3680cc8c.png">
It's happening only with Android 12 devices.
I'm using cast sdk version 21.0.0
Do you have any idea?

**Comment by vpunjabi** [comment]
This issue was resolved in Cast SDK version 21.2.0. You can find the release notes here https://developers.google.com/cast/docs/release-notes#october-10,-2022

If you still run into this issue please reopen
