### ISSUE TITLE
Cast button is no appearing

### ISSUE THREAD

**Issue by hbedford** [googlecast/CastVideos-android#116]
I have aI have a doubt, I'm making an app to transmit his video to any device that receives a transmission, for example a samsung tv, is it with this google cast support that I could do it? because I registered the application there on google cast developer and it didn't help, I added the tv serial and the device. It still doesn't show the button to broadcast, and if I go to the youtube app it appears and works normally

**Comment by c0d3base** [comment]
1. Please make sure you've followed the following:
https://developers.google.com/cast/docs/registration
to register the application and the device. 
2. Publish your app on the Cast Developer Console.
3. Cast the Cast Developer console to your TV and it will show your Serial Number on the screen. Please double check the serial number shown matches the one you registered in the console.
4. Try setting your sender to the Default Receiver and then casting, to see if it works.

Feel free to re-open the issue in case none of the above helps and you need more help.
