### ISSUE TITLE
.ts format live channel not working

### ISSUE THREAD

**Issue by NaveenDevrani** [googlecast/CastVideos-android#119]
Please google add the ".ts" live channel format support

**Comment by c0d3base** [comment]
These are already supported. Please refer to the following documents for further info:

https://developers.google.com/cast/docs/web_receiver/streaming_protocols#segment_format_support
https://developers.google.com/cast/docs/web_receiver/live
https://developers.google.com/cast/docs/media

Please re-open if you need additional help.

**Comment by NaveenMobileProgramming** [comment]
are there any changes from the sender app? I mean in the android app,
 I am passing the '.ts' URL to the chrome cast , it is not able to play. 

please help me with it.
