### ISSUE TITLE
can't reproduce random m3u8 link Chromecast 3 gen 

### ISSUE THREAD

**Issue by jjuandiaz** [googlecast/CastVideos-android#120]
when I send the m3u8 link to the Chromecast the tv show a black screen 
it only happened with random links
 
link for testing 
 
1.- [is reproducible](https://cablevision.trapemn.tv:1936/miscelaneos_transcoder/natgeo.stream/playlist.m3u8)
2.- [cant reproduce](https://cablevision.trapemn.tv:1936/deportes_transcoder/ESPN.stream/playlist.m3u8)

device android 9
device Chromecast 3 generation 
 
[logcat.txt](https://github.com/googlecast/CastVideos-android/files/8413324/logcat.txt)
[proyect sample](https://github.com/googlecast/CastVideos-android/files/8413326/exoPlayer.zip)
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/59715844/161637347-fdc2ae5e-367b-403b-85cf-db77b4904742.png">

 https://i.stack.imgur.com/Eib6M.png

**Comment by c0d3base** [comment]
Looked into this and here's the errors we saw:
natgeo: 
`[cast.player.api.Host] error: cast.player.api.ErrorCode.PLAYBACK/110 (Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp2t; codecs="avc1.64002A,mp4a.6B"') is unsupported.)`
espn: 
`error: cast.player.api.ErrorCode.PLAYBACK/102`

It seems like the codecs you're using aren't supported. Please refer to this doc for the list of [supported media formats](https://developers.google.com/cast/docs/media) and it seems that your content encoding itself is not getting decoded properly.

You can find a description of Error Codes [here](https://developers.google.com/cast/docs/web_receiver/error_codes).

That said, have you tried the [Chrome Remote Debugger](https://developers.google.com/cast/docs/debugging/remote_debugger)? What kind of errors do you get there? Also, are you using your own custom receiver or trying to do this with the default receiver?

**Comment by vpunjabi** [comment]
Please reopen if issue persists
