### ISSUE TITLE
Reverse subtitle and title in mini controller

### ISSUE THREAD

**Issue by emilewakim96** [googlecast/CastVideos-android#121]
Hello,

I want to reverse the title and subtitle texts in the mini controller when casting.

I didn’t find a way to do it. Can someone help me resolve this matter?

Thank you,
Emile

**Comment by c0d3base** [comment]
Currently, there's no out-of-the-box way to do it however, you could:
1. Make you own mini-controller
2. Refer to the [customization guide](https://developers.google.com/cast/docs/android_sender/customize_ui) or 
3. File a feature request using this [link](https://developers.google.com/cast/support#report_issues)

Please re-open if you need additional help.
