### ISSUE TITLE
Local Storage Videos is not casting like content:///storage/emulated/0/DCIM/Camera/VID_20230227_235552.mp4

### ISSUE THREAD

**Issue by adityaec004** [googlecast/CastVideos-android#129]
Hi Team-

How can we do the local storage file cast to TV.
Like this: content:///storage/emulated/0/DCIM/Camera/VID_20230227_235552.mp4
I have tried bt its not working where as http url only working like: https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/DesigningForGoogleCast.mp4
But How can we do below file to cast:
Like this: content:///storage/emulated/0/DCIM/Camera/VID_20230227_235552.mp4

**Comment by adityaec004** [comment]
Getting:::: W/MediaControlChannel: received unexpected error: Invalid Request.

**Comment by QingyunDeng** [comment]
You should start an HTTP service locally and generate a URL for the local video so that the cast server can access it remotely

**Comment by adityaec004** [comment]
Very too late reply
Now I have implemented
Thanks
