### ISSUE TITLE
I integrated chrome cast and see "SAMPLE" in red on the screen?

### ISSUE THREAD

**Issue by ghost** [googlecast/CastVideos-android#14]
Hi,

I followed the instructions and successfully implemented google chrome cast in an android app, using the following libraries:

> ```
> compile 'com.android.support:mediarouter-v7:23.4.0'
> compile 'com.android.support:recyclerview-v7:23.4.0'
> compile 'com.google.android.gms:play-services-cast-framework:9.4.0'
> compile 'com.googlecode.android-query:android-query:0.25.9'
> ```

Currently i am facing an issue where on the screen there is a `overlay of "SAMPLE" text in red` is there a way to remove this?

Thanks!

**Comment by entertailion** [comment]
You've got to create your own app id using the Google Cast Developer Console.
