### ISSUE TITLE
What does setPreloadTime(20) do?  Need help with pre-loading next video / audio in queue.

### ISSUE THREAD

**Issue by ghost** [googlecast/CastVideos-android#15]
Hi,

First of all thanks for this awesome example on how to use the new cast framework.

I successfully implemented Cast in a few applications and am looking for low delay between switching between queue items.  My assumption was when using following code:

```
new MediaQueueItem.Builder(getMediaInfo())
                .setAutoplay(true)
                .setPreloadTime(20)
                .build();
```

especially `setPreloadTime(20)` would load at-least 20 seconds of the next video / audio in queue as soon as the current video / audio just started playing.  Is my assumption correct?

If so,  i am still facing delays between the current video / audio is completed and the next in queue starts (3-5 seconds of delay between current and next).

In my case each media item is between 3 - 40 seconds only and the delay between each media when playing the next item in queue is between 3 - 5 seconds for loading and causing issues.

Would you please guide in reducing this delay and actually pre-load the next video / audio as soon as  the first/current video / audio has started playing?

Thanks!!!

**Comment by entertailion** [comment]
The preload time is a hint passed onto the receiver, for when the next item in the queue should be preloaded. See our reference receiver sample: https://github.com/googlecast/CastReferencePlayer/blob/master/player.js#L513
It is not about how much of the next media is preloaded. You can customize that behavior in your own receiver logic. Also, note that only streaming media formats can be preloaded.
