### ISSUE TITLE
A custom SessionProvider implementation example would be nice.

### ISSUE THREAD

**Issue by mennovogel** [googlecast/CastVideos-android#16]
CastOptionsProvider contains the method getAdditionalSessionProviders(Context context) which can be used to add non-cast devices. The documentation for adding a custom SessionProvider is very limited, so it would be nice if this could be included in this example.

I would like to use this to add support for Samsung's Smartview sdk, just like the YouTube app also has.

**Comment by trolik** [comment]
@mennovogel Did you have any success with smartview integration?

**Comment by mennovogel** [comment]
@trolik I've been in contact with someone working for the Google Cast team. He told me that the Cast SDK is not intended to support libraries like Smartview. It's still not really clear why the method getAdditionalSessionProviders(Context context) is there. 

I have build my own custom View now which supports both Google Cast and Samsung Smartview, this has been a lot of work though.

**Comment by Jogan** [comment]
Any updates on this? I would like to support DLNA/SmartTVs like other apps do. Seems like those havent yet updated to v3

**Comment by w00lyc0dy** [comment]
Hi there,
I am implementing a custom SessionProvider for a non-Cast device. Let me know if you are still interested, I'll throw some code on a github and update the link here (put some kind of info here : http://stackoverflow.com/questions/39148993/how-to-add-a-custom-sessionprovider-with-google-cast-sdk-3).

**Comment by migueltarga** [comment]
@w00lyc0dy Can you share it with us? Thank you!

**Comment by ingsaurabh** [comment]
May I know the reason for closing this one? The issue is valid and yet not solved

**Comment by LeonNicholls** [comment]
This question is outside the scope of the sample. There are links posted in the comments that you can use as a starting point.
