### ISSUE TITLE
Cast reconnection issue

### ISSUE THREAD

**Issue by kevinzetterstrom** [googlecast/CastVideos-android#17]
## Description

When regaining connection to the cast device, the current session does not seem to represent the state of the content on the Cast device. As such, the Cast Videos player state is out of sync with the device.
## Reproduction steps
1. Open the Cast Videos app
2. Connect to a Cast device
3. Select a video -> observe that it starts playing on the receiver
4. Disconnect the client (phone/tablet) from WiFi -> observe video is still playing on the receiver
5. Connect the client back to WiFi -> observe MediaRouteButton shows as connecting -> wait for the connection to establish
6. Press the Pause button
## Actual behavior
- The video is paused on the receiver
- A progress spinner is shown on the client in the app
- The app shows "Loading..."
- The progress/seek bar keeps incrementing
- User cannot play the video again
- The result of CastContext.getSessionManager().getCurrentCastSession().getRemoteMediaClient().isPlaying() returns true
## Expected behavior
- The video is paused on the receiver
- The play button is shown
- The progress/seek bar is stopped in the last position instead of continuously incrementing
- The result of CastContext.getSessionManager().getCurrentCastSession().getRemoteMediaClient().isPlaying() returns false

I am pretty sure this is an issue with the Cast SDK v3 and not the Cast Videos app, but I am not sure where I would voice that concern. In either case, it affects the Cast Videos app, so I decided to write this issue. It affects my application as well, so I am hoping to get this resolved quickly.

**Comment by entertailion** [comment]
You can file a bug against the SDK at: https://code.google.com/p/google-cast-sdk/issues/list

**Comment by Rcureton** [comment]
Did you ever get a solution to this issue because I'm having the same problem and need help?

**Comment by kevinzetterstrom** [comment]
@Rcureton I filed an issue on Sept 7 https://code.google.com/p/google-cast-sdk/issues/detail?id=929 On Dec 8 it was marked as fixed - I believe it should be in newer cast libraries.
