### ISSUE TITLE
Why does LocalPlayerActivity start an ExpandedControlsActivity when cast connects?

### ISSUE THREAD

**Issue by matiash** [googlecast/CastVideos-android#18]
I think it would be more sensible if the video in the LocalPlayerActivity was replaced by a still image, and the play/pause controls managed play/pause on the Chromecast. Basically, the same as YouTube and many other video apps do.

The previous CastVideos sample (the one that used CCL) had this behavior, and (to me, at least) it seemed way more natural.

**Comment by entertailion** [comment]
The Cast Design Checklist doesn't specify this as a requirement and you are welcome to implement this behavior in your app.

**Comment by matiash** [comment]
I understand that. But from the point of view of this being a _sample_, the usability regression is most surprising.
