### ISSUE TITLE
Next queue item preview is not displayed on mini controller

### ISSUE THREAD

**Issue by laurentsebag** [googlecast/CastVideos-android#2]
Using the new version of CastVideos-android and the receiver app sample https://github.com/googlecast/CastReferencePlayer, the next queue item preview is not displayed on the minicontroller.

Reproduction steps:
1. start casting a video
2. add another video to the queue
3. seek to towards the end of the asset

Expected: when the preview of the next item in the queue is displayed on the receiver app, it should be displayed on the minicontroller.

Note: the state of the next episode in the queue screen is updated with a skip button and blue highlight.

---

Tested on Nexus 6 (Android 6.0 MPA44G)

**Comment by laurentsebag** [comment]
Is the new `MiniControllerFragment` meant to automatically display a next item preview row with a skip button like the previous sample sender app (using the Cast Companion Library) used to do when the next video is preloaded?
Or do clients using the Cast SDK v3 now have to implement this via a custom view with `UIMediaController`'s different bind methods?

**Comment by entertailion** [comment]
We are actively looking at how to bring Autoplay views back into the SDK - we know based on data that both content providers and users benefit significantly from well executed autoplay 

We have also received feedback on our queuing functionality - and are evaluating this feedback as many partners use an independent mechanism for queuing than ours - for a variety of reasons 

We hope to align this feedback in the 2nd half of the year for a solution.
