### ISSUE TITLE
Mini controller is sometimes displayed under bottom bar on devices with software buttons

### ISSUE THREAD

**Issue by mihaRLo** [googlecast/CastVideos-android#20]
Steps: 
1. Make sure you are using a device with software bottom butttons (nexus 7, nexus 5x etc).
2. Open CastVideos-android app.
3. Connect to a chromecast.
4. Start video from overflow buttons. 

Behaviour: a shadow appears near the bottom bar, which indicates that the mini controller is present but under the buttons. Please see [screenshot](https://d17oy1vhnax1f7.cloudfront.net/items/101u3L1t1G2Y3V320Y03/device-2016-09-29-161831.png).

Note: this happens sometimes in portrait. In landscape (nexus 7) it happens every time opening a video.

**Comment by entertailion** [comment]
Not able to reproduce this. Mini-controller always shows. Is your Google Play services up to date?

**Comment by daedamr** [comment]
I am using 9.4.0 version. But today i cannot reproduce also anymore, and yesterday it was happening every time on nexus 7 landscape. I will reopen if i find more info. Thanks.
