### ISSUE TITLE
Click on "X" in notification will stop the receiver and disconnect all senders

### ISSUE THREAD

**Issue by nohitme** [googlecast/CastVideos-android#21]
We found this weird issue in notification where if one sender clicks on the "X", the receiver will stop and disconnect all senders.

We observed the same behavior in the latest CastVideos Android builds.

Is this an expected behavior?

It seems wrong to me since we expect the button functions just like "STOP CASTING" button in media route dialog which will only disconnect one sender.

**Comment by entertailion** [comment]
This is by design.
