### ISSUE TITLE
Notification, minicontroller and expandedControllsActivity do not get updated when next item in queue starts

### ISSUE THREAD

**Issue by ghost** [googlecast/CastVideos-android#22]
Here're the steps that produce the issue:
- Play a video
- Add another video into the queue
- Turn off the phone display and throw it away
- When chromecast plays the second video in queue, I turn on the display, but the notification, minicontroller and ExpandedControllsActivity all stay at the end of first video,
  There's no way to get them updated without disconnecting media cast session.

By the way this only happens after putting the display off for quite long time, let's say 20-30 minutes

**Comment by entertailion** [comment]
File a bug against the Cast SDK and provide a complete log: https://code.google.com/p/google-cast-sdk/issues/list
