### ISSUE TITLE
Android Studio stuck at building

### ISSUE THREAD

**Issue by k0shk0sh** [googlecast/CastVideos-android#26]
I'm trying to import the application to android studio but every time i import the application android studio goes into infinite building ( building "gradle" Gradle project info ). 
i don't know how you guys build the application ( assuming you used Eclipse ). could you please use android studio to make the application? or at least provide a way that we can build the sample app without difficulties.

**Comment by naddaf** [comment]
we (along many other people) build using Android Studio and do not have any issues.

**Comment by k0shk0sh** [comment]
@naddaf  well finally i can build it now. the project structure does look like eclipse if you asked me :) .. 
thanks for your response.

**Comment by naddaf** [comment]
yes, the structure looks like eclipse (so people using Eclipse can work with it as well) but otherwise, the build.gradle has the correct info to point to the right src and res and manifest.

**Comment by k0shk0sh** [comment]
@naddaf  i had to build it manually first to be able to import it to android studio. i don't know why but building it manually made it work. thanks for your efforts :+1:
