### ISSUE TITLE
First video does not play when using the default media receiver

### ISSUE THREAD

**Issue by grennis** [googlecast/CastVideos-android#26]
I'm filling this issue here as well as the on code.google.com, not sure where it should go.

If you use the default media receiver (by replacing use of `R.string.app_id` with use of `CastMediaControlIntent.DEFAULT_MEDIA_RECEIVER_APPLICATION_ID` instead), the first video you attempt to cast will not play. Then cast any other video, and it works.

I noticed this problem when developing my own sender app. I then switched to this reference app, and found the same problem.

Testing with Nexus Player 7.0, Build NRD91D

**Comment by LeonNicholls** [comment]
Please file a bug against the Cast SDK: https://code.google.com/p/google-cast-sdk/issues/list
