### ISSUE TITLE
Unable to connect after disconnect media router 

### ISSUE THREAD

**Issue by sachinbhanot** [googlecast/CastVideos-android#27]
HI,

I working on demo project. Where i am trying to connect a chromecast with my application.In my demo app,I am not using action bar.  I need to discover or select the chromecast device manually. I am able to connect with chromecast device on selection a item on list. but when i disconnect the device .. and trying to connect again . but its not working ...I am sharing a code with u. please let me know where i am wrong

**Comment by sachinbhanot** [comment]
Here is code sample :-

https://github.com/sachinbhanot/Chromecast/tree/master/ChromecastSample

**Comment by naddaf** [comment]
Your question doesn't seem to have anything to do with this project; if you have questions on Cast, please ask on StackOverflow.
