### ISSUE TITLE
Listeners for play/pause events on V3

### ISSUE THREAD

**Issue by samramez** [googlecast/CastVideos-android#27]
I need to catch play/pause events when a user is playing a video. 

The current documentation suggests using `MediaIntentReceiver`, however, this would only catch play/pause events when a user clicks it from the lock screen or cast dialogue.

Even` RemoteMediaClient`'s override methods, such as `onStatusUpdated()` and `onSendingRemoteMediaRequest()` doesn't get called when I play/pause the video.

Please advise me on how to add a listener for play/pause in my app.

**Comment by LeonNicholls** [comment]
What is the use case?

**Comment by samramez** [comment]
@entertailion 
I need to make an API call and report the video position, every time video is paused, stopped, or interrupted.

**Comment by samramez** [comment]
@naddaf 
I saw you responded to a Stackoverflow issue while back which was related to mine, but that was for v2 (http://stackoverflow.com/a/38686026/1366145)
Do you happen to know how I can handle it in v3 ?

**Comment by LeonNicholls** [comment]
You can file a feature request: https://code.google.com/p/google-cast-sdk/issues/list
