### ISSUE TITLE
2 notifications

### ISSUE THREAD

**Issue by dima-ko** [googlecast/CastVideos-android#28]
Hello. I have 2nd notification in notification bar. Looks like second one comes from system, so I can't get rid of it. Might be related to http://www.androidpolice.com/2016/11/03/google-play-services-v10-can-show-a-notification-with-player-controls-anytime-a-device-on-the-network-is-casting-apk-download/
Any ideas how to remove it programmatically? 
![device-2016-11-24-204908](https://cloud.githubusercontent.com/assets/1407709/20602712/05e88830-b291-11e6-85b3-d469b267ea65.png)

**Comment by LeonNicholls** [comment]
This is a known bug in Google Play services that will be updated in a future release.
