### ISSUE TITLE
demonstration of ads playback

### ISSUE THREAD

**Issue by StoyanD** [googlecast/CastVideos-android#29]
Would be nice to see how to hook in ads during media playback on the receiver, in particular
AdBreakInfo.Builder

**Comment by lazyFloyd** [comment]
Yes, that would be fine because I found examples only for [Cast SDK v2](https://developers.google.com/interactive-media-ads/docs/sdks/cast/client-side/) and not for the newest one.

**Comment by LeonNicholls** [comment]
We are working on an update for the Cast Receiver SDK that will support ads. For now, you have to use custom messages in your receiver app to integrate with the sender SDK's support for ads.
