### ISSUE TITLE
How to use custom minicontroller?

### ISSUE THREAD

**Issue by perucholly** [googlecast/CastVideos-android#3]
Hi how to use CustomCastMiniController?

Thanks in advanced!

**Comment by entertailion** [comment]
https://developers.google.com/cast/docs/android_sender_advanced#styling_the_mini_controller

**Comment by perucholly** [comment]
Thank you. I had already reviewed . But I find no way to change the color of seekbar.

**Comment by entertailion** [comment]
We will be adding customization options in the next SDK update.
