### ISSUE TITLE
Get UserAgent Chromecast

### ISSUE THREAD

**Issue by dinhhieuac** [googlecast/CastVideos-android#32]
Hi Dev
i can get useragent device chromecast when successful connections?
thanks
hieuhd

**Comment by naddaf** [comment]
Not sure what you are asking here. Besides, is this a generic question or specific to CastVideos-android?

**Comment by dinhhieuac** [comment]
Hi naddaf
I'm using CastVideos-android
thanks
hieuhd

**Comment by naddaf** [comment]
I don't understand what you are asking, sorry. You might want to ask on StackOverflow.
