### ISSUE TITLE
Play/Pause button not working

### ISSUE THREAD

**Issue by gemiren** [googlecast/CastVideos-android#32]
In the sample app, open the casting control dialog by clicking the casting icon on the title bar when video is cast. The pause or play button on the dialog doesn't work. No response when clicking the play/pause button.

**Comment by LeonNicholls** [comment]
The Cast dialog is part of the SDK. If you believe you have found a bug, file an issue with complete log: https://code.google.com/p/google-cast-sdk/issues/list
