### ISSUE TITLE
QueueListAdapter may be 

### ISSUE THREAD

**Issue by akkie2010** [googlecast/CastVideos-android#34]
It seems movement of QueueListAdapter is funny.
If you add a list item that more than than the screen, the behavior of the click is funny.
The order of the item is collapsed.

It is not a big problem, but ...

**Comment by naddaf** [comment]
Just committed a small change; RecyclerView.Adapter prefers to have items with stable ID and just added that; it seems it has fixed the issue; there is still a minor issue with "deleting" items but I suspect that is an issue with the recyclerview and not the app; thanks for reporting this.
