### ISSUE TITLE
some hls cannot play on chromecast

### ISSUE THREAD

**Issue by LukeLinXu** [googlecast/CastVideos-android#35]
Hi,
 
I forked this great repository and I just change the hls url to http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8, and it worked on android and chromecast.

Then I changed url to http://ktv005.cdnak.ds.kylintv.net/nlds/kylin/cctv1hd/as/live/cctv1hd_4.m3u8, it worked on android but not on chromecast. 

I don't know why chromecast cannot support the second hls.

Is it because of format or something?

Thanks,
Luke

**Comment by naddaf** [comment]
The hostnames don't look correct in neither of these two streams, can you
check the urls? Are there any missing dots (".")?

**Comment by LukeLinXu** [comment]
I copied them to vlc, vlc can stream them :)

**Comment by naddaf** [comment]
Looks like your second stream doesn't have CORS header; you can verify that
by running "curl -v <url>", look for the header
"Access-Control-Allow-Origin: *" which means it is supporting CORS and this
is in the first stream's header but not the second one.

**Comment by LukeLinXu** [comment]
Oh, thanks! Finally I got the reason. The second url is a live tv (I don't own it), I just want to cast it on tv, so it seems like currently, we aren't able to do it , correct?

**Comment by naddaf** [comment]
Not necessarily; as long as the format of the stream is supported, Chromecast should be able to play it. As I said earlier, CORS headers are missing so that is the first issue you need to resolve.
