### ISSUE TITLE
Remove Hungarian notation?

### ISSUE THREAD

**Issue by alexbirkett** [googlecast/CastVideos-android#37]
It seems like the old Google convention of prefixing member variables with `m` is used in some places (but not others) in this project. e.g. in `VideoListAdapter` we find 

```java
    private final Context mAppContext;
    private List<MediaInfo> videos;

```
I've not worked on any Android projects that use the `m` notation for many years. Is it still in widespread use? If not can we get rid of it? This would mean that people who begin their implementations by pasting code from the example project would not have to rename everything.

**Comment by LeonNicholls** [comment]
We will continue with the m prefix notation to be consistent with how Android mostly names variables.
