### ISSUE TITLE
Pause/Play Toggle not working on Cast Dialog

### ISSUE THREAD

**Issue by milleph** [googlecast/CastVideos-android#39]
Pause button on cast dialog does nothing. If you implement derived MediaRouteDialogFactory , MediaRouteControllerDialogFragment & MediaRouteControllerDialog  classes as in...

http://stackoverflow.com/questions/42348714/pause-button-not-working-in-android-cast-dialog

Then play/pause works fine...

**Comment by LeonNicholls** [comment]
Please file a bug against the Cast SDK: https://code.google.com/p/google-cast-sdk/issues/list
