### ISSUE TITLE
fully qualified class and package in intent for "cast preference"

### ISSUE THREAD

**Issue by rowntreerob** [googlecast/CastVideos-android#39]
#36 in "application_preference.xml"  

i had to remove the package declaration in order to get it to work.. 

Error prior to my change ... 

```
E/AndroidRuntime(12569): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.google.sample.cast.refplayer/com.google.android.libraries.cast.companionlibrary.cast.tracks.CaptionsPreferenceActivity}; have you declared this activity in your AndroidManifest.xml?
E/AndroidRuntime(12569): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1794)
```

**Comment by naddaf** [comment]
So, have you declared that activity in your manifest?

**Comment by rowntreerob** [comment]
yes.

it would not work with:

https://github.com/googlecast/CastVideos-android/blob/master/res/xml/application_preference.xml#L36

i had to remove the following in order to get rid of the "unable to find
activity class" error

android:targetPackage="com.google.sample.cast.refplayer"

Note that the class in question is already fully qualified in the name
declaration.

if you have time just test it on 6.0.1

**Comment by naddaf** [comment]
I just grabbed a fresh source from GitHub and made no modifications and ran that successfully with no issues; were able to open settings page and open both options there.

Have you made any changes to CastVideos app at all?Is this CastVideos app or your own app?

**Comment by rowntreerob** [comment]
Yes I've modified base project significantly. Recently did upstream merge
to pull your recent mods. That is when I had error. .. Close it out. Sorry .
