### ISSUE TITLE
MiniController attribute

### ISSUE THREAD

**Issue by anna-b** [googlecast/CastVideos-android#4]
Hi!
The attribute "castControlButtons" is not available as it described here: https://developers.google.com/cast/docs/reference/android/com/google/android/gms/cast/framework/media/widget/MiniControllerFragment

One can see in the sources of MiniControllerFragment.class that you might forgot to define it in the attrs:

```
public void onInflate(Context var1, AttributeSet var2, Bundle var3) {
        super.onInflate(var1, var2, var3);
        TypedArray var4 = var1.obtainStyledAttributes(var2, styleable.CastMiniController, attr.castMiniControllerStyle, style.CastMiniController);
        this.nt = var4.getBoolean(styleable.CastMiniController_castShowImageThumbnail, true);
        this.nu = var4.getResourceId(styleable.CastMiniController_castTitleTextAppearance, 0);
        this.nv = var4.getResourceId(styleable.CastMiniController_castSubtitleTextAppearance, 0);
        var4.recycle();
    }
```

May you please check this part? Thank you!

**Comment by entertailion** [comment]
Thanks for reporting. We will fix this in the next release.

**Comment by vokrut** [comment]
But what the right way now to define castControlButtons?

**Comment by entertailion** [comment]
The next SDK update will allow you to use castControlButtons.
