### ISSUE TITLE
MediaMetaData image for Cast Dialog

### ISSUE THREAD

**Issue by milleph** [googlecast/CastVideos-android#40]
Noticing something strange with the cast dialog. Using the MediaInfo.Builder to prepare MediaInfo for a call to RemoteMediaClient.load(mediainfo), if the same image URL is used for MediaMetaData.addImage this time as was used last time the image does not show up in the dialog.

**Comment by LeonNicholls** [comment]
Please file a bug against the Cast SDK: https://code.google.com/p/google-cast-sdk/issues/list
