### ISSUE TITLE
App not compilable

### ISSUE THREAD

**Issue by softvision-mariusduna** [googlecast/CastVideos-android#41]
App not compilable -  gradle says there is no debug configuration

**Comment by naddaf** [comment]
I just grabbed the app, along with CastCompanionLibrary and followed the instructions (used ./gradlew build) and it build with no issues. Make sure your SDK is up to date.

**Comment by softvision-mariusduna** [comment]
the app suppose to compile and deploy directly by the android studio...

**Comment by naddaf** [comment]
When you do "./gradlew build" from command line, does it compile correctly?

**Comment by softvision-mariusduna** [comment]
Finnaly i managed to have it working. Thanks!
One issue out of the subject, I spent entire day and I didn't manage to have ChromecastAudio working, the cast icon is always in disconnected state.

Is is a special setting to have it connected?
For chromecast 2 same code connects to it, For ChromecastAudio the icon is showing as disconnected even if i selected the right route, and using the latest libraries.

```
            MediaRouter.RouteInfo route = (MediaRouter.RouteInfo)getItem(position);
            if (route.isEnabled()) {
                route.select();
                dismiss();
            }
```

**Comment by naddaf** [comment]
There is nothing special about Chromecast Audio vs the regular one in terms of making connection.
