### ISSUE TITLE
Cast button not visible in the actionbar

### ISSUE THREAD

**Issue by ananth10** [googlecast/CastVideos-android#41]
I have installed this sample app on mu mobile . but i can see video list and video list detail screen. but i could not find cast button anywhere. can anyone tell me why is not visible for me?

**Comment by PratikPagada** [comment]
so you got  any solution ?? i facing same issue

**Comment by ananth10** [comment]
@PratikPagada  Yes. You have to register your app and your cast device in Google cast console.

**Comment by PratikPagada** [comment]
@ananth10 Thanks!
