### ISSUE TITLE
How to just mirror whole mobile screen on monitor

### ISSUE THREAD

**Issue by ananth10** [googlecast/CastVideos-android#42]
I am developing an app for TV mirroring. so i just need to mirror everything from mobile to TV(but using HDMI monitor now). i have added cast button in actionbar . when i click button . it displays my chromecast device . when i select it. its connected to my cast but in monitor only that cast icon displaying if exit from app or if open facebook or whatsapp. its not mirror anything.. but i tried with google home app . when i enable cast button . it starts to display my mobile screen to monitor .even if go to facebook .it just mirror and  everything what i do in my mobile  . so how to do like google home app?

**Comment by LeonNicholls** [comment]
Take a look at the Remote Display API.

**Comment by ananth10** [comment]
@entertailion  Thanks you.
