### ISSUE TITLE
Question about audio casting

### ISSUE THREAD

**Issue by chjan** [googlecast/CastVideos-android#42]
Is this library recommended for implementing chromcast audio? Any limitations, things not implemented yet etc? Reason for asking is that the tutorial does not describe audio api usage.

**Comment by naddaf** [comment]
You can use certain pieces of this for an audio app (if that is what you're asking); for example take a look at the [UniversalMusicPlayer](https://github.com/googlesamples/android-UniversalMusicPlayer) sample project that uses CCL.
