### ISSUE TITLE
After integrate cast framework app crashes when opening

### ISSUE THREAD

**Issue by Karthikg206** [googlecast/CastVideos-android#46]
After integrate cast framework app crashes when opening.when google it everyone  says device must update their google play services. How to prevent those errors.

Log says:
java.lang.RuntimeException: com.google.android.gms.dynamite.DynamiteModule$zza: No acceptable module found. Local version is 0 and remote version is 0

**Comment by LeonNicholls** [comment]
You should check that Google Play services is installed and up to date before you initialize the Cast framework: https://developers.google.com/android/guides/setup#ensure_devices_have_the_google_play_services_apk
