### ISSUE TITLE
HLS with wmsauth

### ISSUE THREAD

**Issue by paoloberry** [googlecast/CastVideos-android#47]
Hello, I customized the CastVideos project to parse my m3u playlist and playing my m3u8 files.. When I play locally one of my stream the stream works fine... When i cast my stream it starts to play on chromecast but after 1 mins (but it could varying) it stops to work.. In debug mode i saw a java expection about "malformed URL".. (the stream contains a wms authentication in the form as "https://beta.skystreaming.co/tv/eJx3sUEgLQ/playlist.m3u8?wmsAuthSign=aWQ9NzI5Njg5LWVKeDNzVUVnTFEtMTQ5NTY0NDIxMzExMTAtODguODYuMTg3LjM4JnNlcnZlcl90aW1lPTUvMjQvMjAxNyA0OjQzOjMzIFBNJmhhc2hfdmFsdWU9SElSSVljeWVqT0VVNzFDSjNGaVBHZz09JnZhbGlkbWludXRlcz0yNDA="
It is a hls stream using .ts segment.. if you want i can post you a network packet sniffer to show you the http contents... Btw, i build media info setting mime-type "application/vnd.apple.mpegurl" as showed by http headers.. I was thinking that the problem could be the default receiver app don't using MediaPLayerLibrary to stream hls format,as described in chromecast documentation, but i verified that casting of a Google hls video works fine so my understanding is that receiver app id "4F8B3483" is using MediaPlayerLibrary.. Could you help me what is wrong? thanks
Paolo

**Comment by LeonNicholls** [comment]
This issue is outside the scope of this sample app. You can file an issue in the public tracker: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
