### ISSUE TITLE
Notification image is not cropped

### ISSUE THREAD

**Issue by mennovogel** [googlecast/CastVideos-android#5]
As you can see in the attached screenshot, the notification image is stretched out and not cropped. I assume this behaviour is not intended. I have tested this on several devices and Android versions and most of the devices stretch the image. 
![screenshot_2016-07-19-13-15-42](https://cloud.githubusercontent.com/assets/2795333/16948197/9d4444e6-4db3-11e6-9fbf-f50f8954b645.png)

**Comment by entertailion** [comment]
This is a known issue and will be resolved in a future SDK update.

**Comment by amatkivskiy** [comment]
@entertailion can you tell when are you planning to release that SDK update?

**Comment by amatkivskiy** [comment]
@entertailion Any updates on the current status of this issue?

**Comment by tpiDev** [comment]
Issue is still reproducible with _com.google.android.gms:play-services-cast-framework:9.6.1_ ...

**Comment by entertailion** [comment]
What version of Google Play services are you running?

**Comment by tpiDev** [comment]
@entertailion latest one: com.google.android.gms:play-services-base:9.6.1

**Comment by entertailion** [comment]
No, I mean the version of the Google Play service running on your mobile device (not the SDK library version).

**Comment by tpiDev** [comment]
> Model Number: Nexus 5
> Android version:  6.0.1
> Google Play services Version: 9.6.83 (438-133155058)

**Comment by entertailion** [comment]
The fix should be in the next Google Play services update.
