### ISSUE TITLE
Samsung Galaxy S8 + Chromecast 2 => cannot pause from lockscreen

### ISSUE THREAD

**Issue by alex-schwartzman** [googlecast/CastVideos-android#51]
When I'm running this application on SGS-S8 and casting to Chromecast 2, I experience the minor issue - the pause button on the lock screen is not functional. When the app is in the background, I am able to control the playback only from the notification widget.

**Comment by LeonNicholls** [comment]
The lock screen control is managed by the Cast SDK and not this sample app. Please file a bug against the SDK: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc

**Comment by alex-schwartzman** [comment]
@entertailion I have heard that cast SDK v11 is already available, but the sample app depends on cast SDK v10. What is the timeline for upgrading the sample app to the up-to-date dependencies?

**Comment by LeonNicholls** [comment]
We don't update the samples for every incremental version of the SDK's. If you pull the sample into Android Studio it should help you with any updates.

**Comment by alex-schwartzman** [comment]
I’m afraid I would disagree with that.

As far as I understand, the purpose of this project - is to be part of Cast SDK v3 promotion engine. Therefore, the more up-to date the project is, the better is its promotion score.

I'll create a pull request to upgrade the cast-framework dependency. Hope it will help other Cast SDK adopters in the future.

**Comment by alex-schwartzman** [comment]
Now I see the issue. I cannot upgrade to com.google.android.gms:play-services-cast:11.2.0 because the aar does not contain types of com.google.android.gms.cast.framework namespace. Even though those types are mentioned in the cast SDK documentation, they are not in the package. Seems to be a packaging problem.

I'll come back to you as soon as the packaging problem is resolved on the Cast SDK side.

Thanks for consideration.
Alex.
