### ISSUE TITLE
running the CastVideo App on custom hardware

### ISSUE THREAD

**Issue by harshiddhmania** [googlecast/CastVideos-android#59]
Hi,

I would like to run this CastVideo Sender App on snapdragon 820 based Custom Android hardware. So what are the dependencies to run it on Custom hardware?
Do i need to do the CTS? And licensing and certification also required from Google to run this Cast Sender App?
Thanks in advance.

**Comment by LeonNicholls** [comment]
Cast requires Google Play services. So your hardware would have to be certified by Google.

**Comment by harshiddhmania** [comment]
@entertailion Thanks!
