### ISSUE TITLE
Crash on MiniControllerFragment click

### ISSUE THREAD

**Issue by vinay-altbalaji** [googlecast/CastVideos-android#62]
Hi,

I am using cast framework library version 15.0.1. I have added MiniControllerFragment like this:

`  <fragment
        android:id="@+id/cast_mini_controller"
        class="com.google.android.gms.cast.framework.media.widget.MiniControllerFragment"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:visibility="gone"
        app:castShowImageThumbnail="true" />`

Casting is working properly, but when I click on MiniControllerFragment, app is getting crashed with log mentioned below:

`java.lang.NoSuchFieldError: No field ad_skip_text of type I in class Lcom/google/android/gms/cast/framework/R$id; or its superclasses (declaration of 'com.google.android.gms.cast.framework.R$id' appears in /data/app/com.balaji.alt-2/base.apk)
        at com.google.android.gms.cast.framework.media.widget.ExpandedControllerActivity.onCreate(Unknown Source)`

Can someone please help me with this?

**Comment by LeonNicholls** [comment]
Please file a bug against the Cast SDK: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
