### ISSUE TITLE
Set Style media receiver

### ISSUE THREAD

**Issue by langaliamayank** [googlecast/CastVideos-android#68]
How to register or call Style media receiver in sender application ? 
I want to set splash screen, background. Please help me

**Comment by jtromo** [comment]
To create your own custom receiver with customized UI including a splash screen and background, please follow the CAF Receiver guide: https://developers.google.com/cast/docs/caf_receiver/

**Comment by langaliamayank** [comment]
I have seen given link but I don't know how to call.Did you understand what I want.? 
See I'm sender application I want to set splash screen receiver in sender app. What are the procedure. Share me code how to set assets images or web images.

**Comment by jtromo** [comment]
Please create a custom receiver and point your sender to it as detailed in the integrate cast section of the Android guide: https://developers.google.com/cast/docs/android_sender/integrate#initialize_the_cast_context

To customize your custom receiver please follow the styling the player guide: https://developers.google.com/cast/docs/caf_receiver/customize_ui#styling-the-player

**Comment by langaliamayank** [comment]
How to style the player. ? How to call HTML?
