### ISSUE TITLE
Weird themed color when change colorPrimary

### ISSUE THREAD

**Issue by b95505017** [googlecast/CastVideos-android#7]
If I change colorPrimary to black or red, or using `Theme.AppCompat.Light.DarkActionBar` without override colorPrimary, media router dialog text color is not right.
<img width="551" alt="2016-07-26 12 24 46" src="https://cloud.githubusercontent.com/assets/320815/17108787/8c8c143a-52c7-11e6-81aa-13941ddd658f.png">

**Comment by entertailion** [comment]
Please file a bug: https://code.google.com/p/google-cast-sdk/issues/list
