### ISSUE TITLE
Sample text appeare in tv

### ISSUE THREAD

**Issue by yAhmedIpmagix** [googlecast/CastVideos-android#75]
I have a problem when i cast my video to the screen a SAMPLE word appeared on it how can i remove it ? and thank you

**Comment by simonho1989** [comment]
Maybe Pay $5 dollar?

**Comment by jtromo** [comment]
The app defaults to a sample receiver. Please change the receiver id either to the default receiver or to a receiver you host yourself following the instructions in the README.
