### ISSUE TITLE
[Question]  Remote Display deprecation what should be used

### ISSUE THREAD

**Issue by arpu** [googlecast/CastVideos-android#77]
what is the plan for newer android version and screen mirrow with Remote Display

testing https://developers.google.com/android/reference/com/google/android/gms/cast/CastRemoteDisplayLocalService

but what receiver CAS html/js must be used with this? 
on https://cast.google.com/publish/#/applications/new   i cannot add a new RemoteDisplay  only a Costum Receiver or styled Receiver 

and hint is welcome

**Comment by pascalw** [comment]
I'm looking into using the RemoteDisplay functionality too, but can't find much about it.

[This blogpost](https://developers.googleblog.com/2015/05/announcing-new-google-cast-apis.html) mentions a `Remote Display App ID`, but it doesn't seem possible to register that anymore.

I tried a Custom Receiver, a Styled Media Receiver and the Default Media Receiver but none would show the `CastPresentation`.

@entertailion could you perhaps shed some light on this?

**Comment by LeonNicholls** [comment]
The Remote Display API has been deprecated. We do not recommend any new apps based on this API.

**Comment by pascalw** [comment]
@entertailion ok that's a pity but thanks for confirming!

**Comment by arpu** [comment]
@entertailion  will there be any solution that i can stream the display content? the problem i have is using VP9 video on older chromecast does not work screen casting would be the solution

**Comment by anjaneesh** [comment]
Hello, we don't have an alternative for Remote Display API

**Comment by arpu** [comment]
ok thx for clarification!

any idea what is the best to stream a game screen?

**Comment by josemontiel** [comment]
I'd also like to know about this, is there a way to directly draw on a Cast-enabled screen from an Android App at the moment?

**Comment by kashr** [comment]
Is there a plan for a new API in the future?

**Comment by anjaneesh** [comment]
AFAIK, there is no plan right now. @jtromo Can you confirm please??

**Comment by kmewhort** [comment]
@anjaneesh @jtromo, just want to double-check on whether there's any solution for this? Seems like there's no way to draw a Surface to a chromecast anymore (and thus no way to use it for any interactivity other than straight-up video content)...or is there some other recommended solution?

This is kind of a double-whammy with the Pixel phone disabling HDMI over USB-C.  So users can't even go wired with in order to draw to a larger screen.

**Comment by Mun0n** [comment]
Yeah it would be interesting to have another way to do that, because in my case is the only path to solve my problem. Can't we get more ids for do that? It sounds super bad. 🤕

**Comment by jtromo** [comment]
I can confirm that there is currently no alternative solution for this. If you would like to request it as a feature or have any non-sample related questions/concerns, please use the [Cast Issue Tracker](https://developers.google.com/cast/support#report_issues)

**Comment by Mun0n** [comment]
Ok, i will do that.

https://issuetracker.google.com/issues/157448500

@kmewhort @kashr @arpu @josemontiel @pascalw @entertailion , i would like you to do the same.

Thanks for the support!

**Comment by rajBopche** [comment]
Final words from google over alternative for RemoteDisplay

> Status: Won't Fix (Obsolete)
> Apologies for any discomfort, but we decided to drop support as I mentioned above due to some internal reasons and there is no alternative.

Game Over🙃
