### ISSUE TITLE
MiniControllerFragment

### ISSUE THREAD

**Issue by vokrut** [googlecast/CastVideos-android#8]
In layout player_activity.xml in fragment MiniControllerwe have line:
app:castShowImageThumbnail="true"

It's underscored as mistake in Android Studio: "Add Android prefix".
Can you explain, please, is it right line or not?

**Comment by entertailion** [comment]
Android Studio is a bit confused since it is not taking the class value into account for the custom attributes. The fragment definition is technically correct.
