### ISSUE TITLE
CastVideo Sample App does not show the Cast button

### ISSUE THREAD

**Issue by Sowmya-Flickr** [googlecast/CastVideos-android#85]
I am using the github repo and just trying to run the sample Cast App. The app does not show the Cast button. Am i missing some any configuration here? The sample app already has an APP ID. Does it need to be changed? 

Any ideas will be much appreciated.

**Comment by anjaneesh** [comment]
Try to run the repo on a physical device, I just tried and seems like it is not working on emulator as of now but works with the physical device. We will look into it.

**Comment by Sowmya-Flickr** [comment]
I am running it on Samsung Galaxy S10 running Android 9, its not showing the Cast button

**Comment by anjaneesh** [comment]
@jtromo did we make any changes to this ? Can you look into this please.

**Comment by jtromo** [comment]
There were no changes since July of last year. I just tested on my phone (Pixel 4 Android 10) and was able to see all of the devices on my network. Please make sure you are on the same network as your devices.

Note that on Android the emulator does not work for device discovery, but on iOS the simulator does.

**Comment by brindhamaran235** [comment]
I am running  a physical device ,above Android 8, its not showing the Cast button

**Comment by i-kazimrizvi** [comment]
Same issue, not able to see the cast button on physical devices. Tested with Android 7 and 10.
The Youtube cast is working.

**Comment by jtromo** [comment]
I just verified that the sample is working properly and displaying the Cast button. Please try using the receiver app ID provided with this sample "4F8B3483".

Also make sure that your devices are registered on https://cast.google.com/publish/#/overview. If you are having trouble with your own app, you can also try publishing your receiver to try to get the Cast button visible.
