### ISSUE TITLE
Cast Android 19.0.0 regression on audio groups

### ISSUE THREAD

**Issue by Tolriq** [googlecast/CastVideos-android#98]
There's no way to contact any support team and this will be ignored but let's try.

Since updated to Play Cast 19.0 on Android, playing media on an audio group does not start the media but leave them paused. Still works when casting directly to devices and works OK when reverting to previous version.

**Comment by c0d3base** [comment]
Hey thanks for bringing this to our attention however, for such issues best way to go about is by reporting them to the [issue tracker](https://developers.google.com/cast/support#report_issues). This is actively monitored for SDK issues by our team.

Github issues are only pertaining to the samples and is not monitored as closely.
